### PR TITLE
t1ha: sync with mainstream.

### PR DESCRIPTION
**Pull request by leo-yuriev**
- fix tail align optimization.
 - update README and comments.
 - minor refine.

### CODE REVIEW

**Comment by Bulat-Ziganshin** [comment]
i think i've already seen hashes trying to employ _mm_crc32_u64 for larger hashes. but note that this instruction consumes 8 input bytes and returns only 4, so any 8+ byte hash will have 2^32 collisions on any input qword. Even if it can successfully pass SMHasher tests, this tells more about quality of tests rather than quality of hash :)

**Comment by leo-yuriev** [comment]
@Bulat-Ziganshin, _mm_crc32_u64 can be used safely, if there is enough avalanche effect over an internal state.
In general, any hash will compress a lot of input into a few bits of internal state and then to output.

**Comment by Bulat-Ziganshin** [comment]
Imagine a 32-bit hash that maps all possible values of first source dword into 2^16 hash results. is this hash good for using in a table with 2^32 entries? definitely not. the same applies to 64-bit hash producing 2^32 results from 2^64 values of the same qword. meanwhile, i looked into smhasher reports and expect that such hash will fail many tests. do you tried?

**Comment by leo-yuriev** [comment]
Of course, t1ha_ia32crc() passes all tests without complaints. You can chech this by my [mshasher fork](https://github.com/leo-yuriev/smhasher-rurban).

You are talking about trivial mapping which should not be used to avoid problems. Simply put, the _mm_crc32_u64 is only used for convolution of long data, but only in a loop with nonlinear feedback and mixing. It provides a reasonable avalanche effect for all 128 bits of internal state. Please see [the code](
https://github.com/leo-yuriev/t1ha/commit/44973f48d40c2e33c774be0a53c1159ed0a466be#diff-4bd3d63c25c1ad0315919cbfe1fce047R777).

**Comment by rurban** [comment]
If you are fine with it, I'm fine with it also.
Just beware that a hash which returns platform specific values is not really of much use in portable apps, which need to transport their hashes across platforms. Such as a checksum in data files.

t1ha is the only hash with this deficiency.
So I will note it as NON-PORTABLE or ARCH-SPECIFIC.

**Comment by leo-yuriev** [comment]
@rurban, think I should clarify.

1. the `uint64_t t1ha(const void *data, size_t len, uint64_t seed);` is **still portable and not arch-specific**.
2. now I added `t1ha_64be()`, `t1ha_64le()`, `t1ha_32be` and `t1ha_32le()` - also all are portable and not arch-specific, but just run afster on a 'native' arch.
3. also I added `t1ha_ia32crc()` and later will `t1ha_ia32aes`, which all together will be bundled into `t1ha_local()`.

So, in general, **only `t1ha_local()`** is non-portable and arch-specific, and will returns platform specific values.

**Comment by Bulat-Ziganshin** [comment]
let's check where we disagree:
- 32-bit hash providing only 16 bits of entropy (i.e. having only 2^16 unique values) is bad
- 64-bit hash providing only 32 bits of entropy is bad
- 64-bit hash extracting only 32 bits of entropy from first 8 bytes of input (i.e. having only 2^32 unique values on inputs with all possible first 8 bytes and fixed remainder) is bad

your hash extracts only 32 bits of entropy from most of input qwords. you are pushing its good avalanche effect, but it's only **one of** properties required for good hashing. good 64-bit hash should also project each 64 input bits **reversibly** into its internal state and only then start to mix data among this (larger than 64 bit) state. Please read:
- "A common weakness" part [here](http://www.burtleburtle.net/bob/hash/doobs.html)
- "Funneling" part [here](http://burtleburtle.net/bob/hash/evahash.html) (it's the same work, just modified over the years)

In particular, the following directly addresses your case:
> Any time n input bits can only affect m output bits, and n > m, then the 2^n keys that differ in those input bits can only produce 2^m distinct hash values. The same is true if n input bits can only affect m bits of the internal state -- later mixing may make the 2^m results look uniformly distributed, but there will still be only 2^m results.

It's what i call "extracting m bits of entropy from n input bits", and for 64-bit hash, you should extract full 64 bits of entropy from each 64-bit portion of input data. If only 32 bits are extracted, it can qualify only as 32-bit hash.

**Comment by leo-yuriev** [comment]
@Bulat-Ziganshin, you are quite right. 

This is obviously that any approach with a CRC-compression could not provide properly gathering of entropy. So, it is possible to make a test which will be detects "reduction" on entropy into the 32 bit (width of CRC). And such test would be a great addition to SMHasher.

But on the other hand, this is just a tradeoff between speed and quality of hash function. It is possible to show that any fast (not complex) function has flaws in the entropy sponge, and so, in some cases may produce more collisions than usual.

So, in general, I think that a crc32c is not a very right approach, but may be a reasonable in some applications.

**Pull request merged**
