### PR TITLE
Update beamsplitter

### PR DESCRIPTION
**Pull request by cris691**
Passes all tests. Fast ~ 900Mb/s

### CODE REVIEW

**Comment by rurban** [comment]
I'll squash it, OK?

**Comment by cris691** [comment]
Definitely!

**Comment by rurban** [comment]
Updated the results, indeed impressive. Not the speed, but the quality

**Comment by cris691** [comment]
Thanks :smile:

If you want to try to make it faster, go for it. 

I tried a few things to crack 1 GB/s, couldn't.

**Pull request merged**
