### PR TITLE
Fixes for issue #24

### PR DESCRIPTION
**Pull request by leo-yuriev**
1. Replaces SHA1 implementation, now passed sanity checks.
2. Adds seeding support for md5_32 and sha1_32.

### CODE REVIEW

**Comment by leo-yuriev** [comment]
now use `uint8_t`, and applies clang-format.

**Comment by vstakhov** [comment]
BTW, your sha1 implementation is broken on Sparc64 (perhaps, on other BE platforms as well). MD5 is still fine.

**Comment by rurban** [comment]
@leo-yuriev: Do have access to a BE architecture? You broke it.

**Comment by leo-yuriev** [comment]
fixed, please merge #26

**Comment by rurban** [comment]
Done better. Thanks

**Pull request merged**
