### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by thomasahle**
Fixes Issue #156

### CODE REVIEW

**Comment by rurban** [comment]
Yeah, I disagree a bit. See #156.

Which issues did you see with t1ha2_atonce? For me I see none, but maybe you use a different HW version.

**Review by rurban — CHANGES_REQUESTED** [review]
Still insecure. See GH #156

**Comment by thomasahle** [comment]
The readme currently says "Zeroes low3" and "LongNeighbors". Maybe that's just not updated?

**Comment by wangyi-fudan** [comment]
BTW: it seems wyhash is the faster than xxh3low. should me update the rank in readme?

**Pull request closed without merging**
