### PR TITLE
Update MetroHash

### PR DESCRIPTION
**Pull request by data-man**
Currently SMHasher uses a legacy algorithm.
Time to change it. :)

### CODE REVIEW

**Comment by data-man** [comment]
The code taken from https://github.com/jandrewrogers/MetroHash so metrohash64crc_1 and metrohash64crc_2 are removed.

**Comment by rurban** [comment]
Oh no, I liked the 64crc parts, esp. _2.
Will see what I can do

**Comment by data-man** [comment]
metrohash64crc_* are back.

**Comment by rurban** [comment]
Thanks!

**Pull request merged**
