### PR TITLE
Hashmap test

### PR DESCRIPTION
**Pull request by wangyi-fudan**
Dear rurban:
  Based on your hashmap test, I found wyhash could be the fastest if I remove a few lines. Also the number of runs could be increased to 100 to obtain accurate speed measure, but not significantly increase time cost.

### CODE REVIEW

**Comment by wangyi-fudan** [comment]
BTW, bytell_hash_map (https://github.com/skarupke/flat_hash_map) is the fastest hash map avaiable using c++14. I found wyhash+bytell_hash_map is the fastest one.

**Comment by rurban** [comment]
I also checked various other much faster hashmaps, such as e.g. from rigtorp, but settled with the slow standard for fair comparison purposes.

**Comment by rurban** [comment]
Changed verification values with !WYHASH_UNSAFE. I'll fix it.

**Comment by dumblob** [comment]
Speaking about currently worldwide available hashmaps, definitely skim the comparison from Martin Ankerl https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-05-conclusion/ to notice one very important thing. Namely that some hashmaps are almost not at all sensitive to collisions and throughput and latency ([Throughput versus latency](http://fastcompression.blogspot.com/2019/03/presenting-xxh3.html )) of the hash function, but other hashmaps rely **completely** on the quality and throughput and/or latency of the hash function.

To be fair in showing real use case scenarios, we would actually need to test one representative from the sensitive corner and one from the insensitive corner.

**Comment by rurban** [comment]
True. There should be a linear probing one also. 

And we need to add the stddev to the mean cycles. I'll also add the initial insert/delete timings, but without trials and outlier removal.

**Pull request closed without merging**
