### PR TITLE
Fix #191

### LINKED ISSUE #191: UB reproducibility
Hey @rurban 

Thanks a lot for your work on SMHasher. It's really changed a lot in the last 3 years, all because of the effort you put in. The project's so much bigger than it was before, and better, thanks to your effort. I, and I'm sure a lot of others, really appreciate what you're doing.

Anyway, I'm sure you're super busy so I get if you can't get to this, or if anything makes it impossible for you and that's cool, everyone's got different degrees of freedom there, but I was just wondering about something and I have a pretty stupid question so I'm sorry.

Question is: how do I reproduce the "UB" claims you make against some of the hashes? Specifically I'm trying to repro on my hashes discohash and beamsplitter so I can try to address the UB flags you put against them. I tried,

```console
$ clang++ -fsanitize=undefined *.cpp
```
on my discohash repo and it compiled fine. Sorry I'm not an expert in this and I know it's not your job, so if you can't reply that's cool. I'm just wondering, how do I do it like you did it so I can reproduce the behaviour you're seeing?

Anyway, I get if you're too busy to reply or if anything else means you can't get to this and that's cool, everyone has different degrees of freedom there,  I wish you all the best in SMHasher and have a great 2021!

Cris

### PR DESCRIPTION
**Pull request by 00000o1**
Hi @rurban 

Long time! Hope you're doing well. I see smhasher has continued to grow and become so much more! That's great! 

I think this fixes the memory alignment issues of discohash (#191). If it does, turns out the fix was quite simple, just using `alignas`. 

Also, just for interest: I tried using `CXX=clang++` and found it produces results that are about 15% faster, so I'm throwin' it it out there! 

I know you're super busy so no worries if you have no time to get to this PR, just thanks for reading this far!

### CODE REVIEW

**Review by rurban — COMMENTED** [review]
static inline would be even better

**Comment by 00000o1** [comment]
@rurban Alright man I'll jump on that!

I tried adding `-DCMAKE_BUILD_TYPE=Debug` but then running `SMHasher BEBB4185` said BEBB4185 was an unknown hash. I couldn't find the place to change that so I just assumed it was taken out of circulation for Debug due to its undefined behavior maybe! :)

**Comment by 00000o1** [comment]
@rurban done!

**Review by rurban — CHANGES_REQUESTED** [review]
But you cannot change build.sh. This is for speed

**Comment by 00000o1** [comment]
@rurban done! Changed build.sh back to normal and also aligned the input `void *key` :S !

**Comment by 00000o1** [comment]
@rurban RAA! It is DONE! ✌🏻

**Comment by 00000o1** [comment]
@rurban hey man I'm sorry this will probably give you a lot of trouble, so I'm sorry to bug you with this request, but i was wondering, can we retire the name BEBB4185 and now call it discohash  ? This is inline with https://github.com/dosyago/discohash and I think it's easier to catch if it uses a real human English name not a hex value! :)

**Review by rurban — CHANGES_REQUESTED** [review]
Now squash it all, rename to discohash and we are done

**Comment by 00000o1** [comment]
Yes sir! 🫡

**Comment by 00000o1** [comment]
Alright, @rurban it is TRULY NOW DONE THIS TIME! :) 

Would it be a terrible idea to re-run the hash quality tests? I noticed it's faster!

**Review by rurban — APPROVED** [review]

**Comment by rurban** [comment]
At home it is slower. Will test at the benchmark machine on mondays

**Comment by 00000o1** [comment]
@rurban makes sense, because it added alignment. I only tested on a new machine, was surprised at the speed. Didn't benchmark the old tho!

**Pull request merged**
