### PR TITLE
Add BEBB4185 results

### PR DESCRIPTION
**Pull request by cris691**
First try. Re #105, @rurban

### CODE REVIEW

**Comment by rurban** [comment]
The code is missing, and the changes to main.cpp and Hashes.h

**Comment by cris691** [comment]
Nah those changes are merged previously

eg https://github.com/rurban/smhasher/blob/c45806e273489d003aed91c453df37ec9463f773/main.cpp#L201

**Comment by cris691** [comment]
Also https://github.com/rurban/smhasher/blob/c45806e273489d003aed91c453df37ec9463f773/Hashes.h#L966 re @rurban

**Comment by rurban** [comment]
Ah ok, was on my phone only. Will check.

**Comment by cris691** [comment]
Sounds like you don't have much room to move on this. Would you be unwilling to take a look today?

**Pull request merged**
