### PR TITLE
Add jodyhash v5 32-bit/64-bit

### PR DESCRIPTION
**Pull request by jbruchon**

### CODE REVIEW

**Comment by rurban** [comment]
Nice, thanks

**Comment by jbruchon** [comment]
I've removed the repo for this hash since SMHasher shows serious problems with its behavior. Feel free to revert this pull request if you wish; apparently no one is using jodyhash so now it's a waste of space. Apologies for the trouble.

**Comment by rurban** [comment]
Na, it's not a good hash function, but also not a really bad one. It's still better and faster than the most widely used hash functions FNV1, djb, smdb, x17, JenkinsOOAT, MicroOAAT.
No troubles at all.

**Comment by Bulat-Ziganshin** [comment]
@jbruchon, the entire point of SMHasher is to show quality of hashes to anyone choosing hash for his app. Removing hash will mean lack of information rather than information that the hash is weak.

**Pull request merged**
