### PR TITLE
change blake3 code to be compatible with non C99 standard.

### PR DESCRIPTION
**Pull request by vakninyogev**
Blake3 had some declarsions inside for loops, which prevent it from building.

### CODE REVIEW

**Comment by rurban** [comment]
Not really. Either put the decl first, but we require C99 everwhere. Which compiler failed for you?

**Comment by vakninyogev** [comment]
> Not really. Either put the decl first, but we require C99 everwhere. Which compiler failed for you?

I used the build.sh script, which run gcc (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)).
got the following:
/home/centos/smhasher/blake3/blake3.c: In function 'blake3_hasher_update':
/home/centos/smhasher/blake3/blake3.c:249:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (size_t chunk_index = 0; chunk_index < num_chunks; chunk_index++) {
     ^
/home/centos/smhasher/blake3/blake3.c:249:5: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [CMakeFiles/SMHasherSupport.dir/blake3/blake3.c.o] Error 1
.....

if you want I can add -std=c99 to the compilation instead

**Comment by rurban** [comment]
I see. Better would to be to fix this upstream over at BLAKE3-team/BLAKE3

**Comment by rurban** [comment]
Fixed differently in 19402153f9715555086bf2ffec3bbbda7d76fb71
Thanks nevertheless

**Pull request closed without merging**
