### PR TITLE
Polynomial hashing

### PR DESCRIPTION
**Pull request by thomasahle**
I have added a fast implementation of Polynomial Hashing from https://arxiv.org/abs/2008.08654
The poly_2 function fails Avalanche, Window and MomentChi2.
The poly_3 function completes all tests.
It is also possible to use higher degree polynomials, but it isn't necessary for any of the tests.

### CODE REVIEW

**Comment by rurban** [comment]
Good, but can you rebase onto master?

**Comment by thomasahle** [comment]
Sorry, it should be good now.

**Comment by rurban** [comment]
I got good results for 2. Only poor for 1, which fails most tests.
I've added the 1 and 4 results also.
Thanks!

**Comment by rurban** [comment]
Merged

**Comment by thomasahle** [comment]
I'm interested in understanding in ubsan problem better. Is this specific to a specific set of hardware?

I suppose the security model of those hash functions doesn't include the "attacker" having access to the seed/random values used in the function.

The current setup is a bit confusing, since there are two seeds: The one from _seed_init(s) and the one given at every call the the hash function. The first one is mixed in much more carefully, while for the second I just aim to be efficient. I imagine the first one is what you would use when rehashing a hashmap, say.

**Comment by thomasahle** [comment]
Do you a recommended hash I can look at for how best to solve the unalignment problem?

**Comment by thomasahle** [comment]
Another note on the security: I'm not quite familiar with the "the random seed is known" model, but would it be better if I added the seed at the beginning, rather than the end? Then it would be slightly more work to figure out how to cancel things out.

**Comment by rurban** [comment]
> I'm interested in understanding in ubsan problem better. Is this specific to a specific set of hardware?

Yes. Some older cpu's throw sigbus errors, mostly sparc and old arm's. But mostly it's ubsan now, which is merely annoying. That's why I added the HAVE_ALIGNED_ACCESS_REQUIRED probe. You can then ifdef the alignment step out.
I did it recently on FNV2.

**Pull request closed without merging**
