### PR TITLE
smhasher: fix big-endian for sha1.

### PR DESCRIPTION
**Pull request by leo-yuriev**
just copy LE/BE checks from t1ha.c

### CODE REVIEW

**Comment by leo-yuriev** [comment]
wait please, I found a bug

**Comment by leo-yuriev** [comment]
ready now

**Comment by vstakhov** [comment]
One more note: there is no sparc and itanium checks, so such code won't even compile. In theory, you can use https://sourceforge.net/p/predef/wiki/Architectures/ or just test for machine defined endiannes.

**Comment by leo-yuriev** [comment]
@vstakhov, pleasee see https://sourceforge.net/p/predef/wiki/Endianness/

Detection of endianness by arch-related predefines - it is not good idea, In general.
I was added few such checks internally in t1ha (for instance __ARMEL__) only for embedded platform, which historically not provides endianness definitions. 

But on other hand I missed sys/param.h and checks for the legacy __LITTLE_ENDIAN/_BIG_ENDIAN predefines (Elbrus case).
Now this is fixed.

**Comment by vstakhov** [comment]
Is there any evidence that `sys/param.h` should define the byte order? Because in my case I had to check for headers like `sys/endian.h`, `machine/endian.h` and `endian.h` to do that. If you are right then I could remove those checks.

**Comment by rurban** [comment]
@vstakhov yes, this should be cmake rule, as in https://stackoverflow.com/questions/3877344/detect-endianness-with-cmake

**Comment by rurban** [comment]
I did it a little bit different than that, because compile-time endian testing is not so easy (multiple headers to probe per architecture) and I'd rather have cmake do that.

**Comment by leo-yuriev** [comment]
0xDCB02360 should not be changes for sha1_32w when runs on little-endian.
Guess I the bug is here = https://github.com/rurban/smhasher/commit/93169294cd209fc4e0cc752943f1d02f53993c27#diff-af3b638bc2a3e6c650974192a53c7291R22

Only flags for C-sources will includes -DBIG_ENDIAN, but sha1.cpp will be compiled as C++.
So, it be always compiled without -DBIG_ENDIAN.

**Comment by rurban** [comment]
Ouch, good catch. thanks

**Comment by rurban** [comment]
done

**Pull request closed without merging**
