### PR TITLE
Hash updates

### PR DESCRIPTION
**Pull request by cris691**
"Changes look good. Clean branch"

I found some issues sometimes with using const I suppose because it can be optimized unexpectedly by the compiler. So removed it. 

Also add the verification value for floppsyhash

### CODE REVIEW

**Comment by rurban** [comment]
The floppsyhash verification value is wrong on clang and 32bit

**Comment by cris691** [comment]
Sorry, I didn't know about that. It makes sense tho, because it uses
floating point so it tightly coupled to arch/implementation.

Best revert to your fix, "SKIP", which I didn't understand before. THanks
for explaining, sorry for changing it back! :)

**Comment by rurban** [comment]
This should do it

**Comment by cris691** [comment]
Cool

**Comment by cris691** [comment]
💯

**Pull request merged**
