### PR TITLE
Fixes bad seeding from Issue 156

### PR DESCRIPTION
**Pull request by thomasahle**

### CODE REVIEW

**Review by rurban — CHANGES_REQUESTED** [review]
Nope, totally wrong. Ths skip the seed init for all

**Comment by thomasahle** [comment]
No, if you have
```
if (false)
    ;
else if (A)
    ...
else if (B)
    ...
```

Is equivalent to  
```
if (A)
    ...
else if (B)
    ...
```

Before this patch we had
```
if (true)
    ;
else if (A)
    ...
else if (B)
    ...
```
which skips every seed.

**Comment by rurban** [comment]
Thomas Dybdahl Ahle <notifications@github.com> schrieb am Mo., 21. Sep.
2020, 15:45:

> No, if you have
>
> if (false)
>     ;
> else if (A)
>     ...
> else if (B)
>     ...
>
> Is equivalent to
>
> if (A)
>     ...
> else if (B)
>     ...
>
> Before this patch we had
>
> if (true)
>     ;
> else if (A)
>     ...
> else if (B)
>     ...
>
> which skips every seed.
>

Oops. Major blunder!
Sorry to have the wrong tags then on your hashes.

I'm still a bit busy now, hope to get to it tomorrow.

**Comment by rurban** [comment]
Fixed differently, thanks

**Pull request closed without merging**
