### PR TITLE
Several improvements and bugfixes

### PR DESCRIPTION
**Pull request by Cyan4973**
These are changes introduced during development of xxh3 and xxh128 for both convenience and more thorough testings.

Notable changes : 
- Command line : support multiple arguments, in any order. Better detection and message no argument errors.
- Extended MomentChi2 test : now control both bit0 and bit1, raw and derivative values. Input length can also be selected. Check result against a precalculated "optimal" value (previously, would only ensure that both `input` and `seed` drift synchronously, allowing a hash like `donothing` to pass the test successfully)
- New Perlin Noise test
- New Prng test
- updated xxh3 & xxh128 implementations to latest release (`v0.7.3`). Updated their corresponding results.

### CODE REVIEW

**Comment by rurban** [comment]
Can you fix the windows problem? main.cpp(1337): error C2131: expression did not evaluate to a constant

**Comment by Cyan4973** [comment]
Sure! Should be fixed now.
It was a small VLA on stack. I'm a bit surprised, Visual Studio 2017 is supposed to support this C99 idiom by now ?
Anyway, replaced with a fixed size one, with an additional size verification.

**Comment by rurban** [comment]
A ifdef MSC_VER would have also been ok, but I heard VLA fell out of favor.

**Comment by rurban** [comment]
I rebased it and re-enabled the last bits tests, which are useful to test the quality in typical non-prime hash tables.

**Comment by Cyan4973** [comment]
oh indeed, I forgot that one.
Indeed, it was disabled, as the result was basically always the same (table saturated).

While it's fine to have a test specifically dedicated to the last N bits, I believe it should be different test : testing the nb of collisions learns us basically nothing, but testing the distribution of collisions (aka how many hashes per bucket) would be more meaningful.

**Pull request closed without merging**
